### ISSUE TITLE
Skrócenie nazw plików *.png

### ISSUE THREAD

**Issue by smudap** [pbiecek/TechnikiWizualizacjiDanych#144]
Czy byłaby możliwość skrócenia nazw plików z tego folderu:
https://github.com/pbiecek/TechnikiWizualizacjiDanych/tree/master/MINI_2016/Projekty/Projekt01/faza_final/sobczakm_szczekutekr_tenderendap/wykresy ?
SourceTree nie chce pobrać mi ich na dysk, bo nazwy są zbyt długie. Przez to nie mogę wrzucić plików przez SourceTree na swoje sforkowane repo.

**Comment by pbiecek** [comment]
pliki z polskimi literami w nazwach zostały spakowane, nazwy są krótsze, nie powinno być problemu
